// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuCYeG9-ORIxK0N-MQ2fYnZ36W5lPFV4',
    appId: '1:523956890809:web:7a2daea6272a7598ef3f68',
    messagingSenderId: '523956890809',
    projectId: 'agroconnect-dcd0f',
    authDomain: 'agroconnect-dcd0f.firebaseapp.com',
    storageBucket: 'agroconnect-dcd0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKtvVJc3u9rxRPUcSR3CXT4fmA-t74Tk',
    appId: '1:523956890809:android:aa34dca7050acbf7ef3f68',
    messagingSenderId: '523956890809',
    projectId: 'agroconnect-dcd0f',
    storageBucket: 'agroconnect-dcd0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACG1hG8HsKjxtm2lpFEe2rU80QdiP78Zo',
    appId: '1:523956890809:ios:9a67549108770225ef3f68',
    messagingSenderId: '523956890809',
    projectId: 'agroconnect-dcd0f',
    storageBucket: 'agroconnect-dcd0f.firebasestorage.app',
    iosBundleId: 'com.example.agroconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACG1hG8HsKjxtm2lpFEe2rU80QdiP78Zo',
    appId: '1:523956890809:ios:9a67549108770225ef3f68',
    messagingSenderId: '523956890809',
    projectId: 'agroconnect-dcd0f',
    storageBucket: 'agroconnect-dcd0f.firebasestorage.app',
    iosBundleId: 'com.example.agroconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjuCYeG9-ORIxK0N-MQ2fYnZ36W5lPFV4',
    appId: '1:523956890809:web:74193a33f1fc75aaef3f68',
    messagingSenderId: '523956890809',
    projectId: 'agroconnect-dcd0f',
    authDomain: 'agroconnect-dcd0f.firebaseapp.com',
    storageBucket: 'agroconnect-dcd0f.firebasestorage.app',
  );
}
